version: '3.7'

services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ../data/:/data
      - ./config.json:/polar-flow-export/config.json
 #     - ./polar-export.py:/polar-flow-export/polar-export.py # Testing with local version

